inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'spec/support/protos/*.pb.rb'
    - 'varint_prof.rb'

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Lint/Loop:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Style/ClassAndModuleChildren:
  Exclude:
    - '**/*.pb.rb'

Naming/ClassAndModuleCamelCase:
  Exclude:
    - '**/*.pb.rb'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EmptyLines:
  Exclude:
    - '**/*.pb.rb'

Naming/FileName:
  Exclude:
    - '**/protoc-gen-ruby*'

Style/GuardClause:
  MinBodyLength: 4

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineBlockParams:
  Enabled: false

Layout/TrailingEmptyLines:
  Exclude:
    - '**/*.pb.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  AllowDSLWriters: true
  AllowPredicates: true

Style/Encoding:
  Exclude:
    - '**/*.pb.rb'
